name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - '*/**'
      - '!badges/**'
      - '!README.md'
  workflow_dispatch:

jobs:
  build:
    name: Build for AMD64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - v4.2.2
          - v4.1.0
          - v4.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: "gcavalcante8808/upx:${{ matrix.version }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            UPX_VERSION=${{ matrix.version }}
